server:
  port: 5555
jwt:
  accessTokenValidMS: 3600000
  refreshTokenValidMS: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    base-package: "com.ssu.commerce.delivery"
    title: Delivery
    version: 0.0.0